<?php

namespace BisonLab\ProductMasterBundle\Entity\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * ProductCampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCampaignRepository extends EntityRepository
{
}